### ISSUE TITLE
Indicator groups only have no2

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/covid-dashboard#280]
This seem to be some sort of regression.
The indicator groups are all empty, with the exception of Air quality which only has NO2

https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/indicator_groups
![image](https://user-images.githubusercontent.com/1090606/85389656-a1c79480-b53f-11ea-9665-b2082f2e59e4.png)

**Comment by olafveerman** [comment]
No regression. At the moment we only have indicator data for NO2.

By launch, we still want to have: chart data for CO2

**Comment by vgeorge** [comment]
In order to show indicators with no chart they should be present in this endpoint response, otherwise they can't be included in the appropriate accordion. This is blocking https://github.com/NASA-IMPACT/covid-dashboard/issues/167 until we include `nightlights` in `economic` indicator group.

I also noticed that `ship-detections` indicator is missing, but not sure if that is intentional.

**Comment by olafveerman** [comment]
This is fixed and will be available soon. https://github.com/NASA-IMPACT/covid-api/commit/7a3095f8c90f833ecdbdf03320fa291259e0c77c
