### ISSUE TITLE
Invalid time values

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#448]
https://earthdata.nasa.gov/covid19/explore/sf?map=-122.3218%2C37.7334%2C11.63&layers=no2-diff&lState=nightlights-hd%7C0%7C0%2Cdetections-ship%7C0%7C0%2Cno2-diff%7C0%7C0

results in:

![image](https://user-images.githubusercontent.com/751330/98805257-35c2cb80-240f-11eb-9ef7-1140f9901d2c.png)

* NO2 Diff
* Agriculture

**Comment by olafveerman** [comment]
For agriculture, the API returns an empty array for the date domain.
For NO2 Diff, the tile url gives a 500 internal server error.

**Comment by olafveerman** [comment]
Tracking NO2 in a separate issue.

Config for agriculture returned from the API:

``` json
{
    "id": "agriculture",
    "name": "Agriculture",
    "type": "raster-timeseries",
    "isPeriodic": true,
    "timeUnit": "month",
    "domain": [],
    "source": {
      "type": "raster",
      "tiles": [
        "https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/{x}/{y}@1x?url=s3://covid-eo-data/agriculture-cropmonitor/CropMonitor_{date}.tif&resampling_method=nearest&bidx=1&color_map=custom_cropmonitor"
      ]
    },
    ...
}
```

Originally I thought this was due to the date formatting of the COG, which does not follow the convention of the other monthly datasets. But even after changing all the filenames on S3, the domain is still empty.

`CropMonitor_2020_10_28.tif` -> `CropMonitor_202010.tif`

**Comment by leothomas** [comment]
Agriculture looks for data in s3 subfolder `s3://covid-eo-data/agriculture-cropmonitor` (as opposed to `s3://covid-eo-data/agriculture`). The reason for this was because originally, the `s3://covid-eo-data/agriculture/` folder had a bunch of different files (other can `Cropmonitor*` which were causing invalid dates to be returned, so I moved all `agriculture/Cropmonitor*` files to `agriculture-cropmonitor`. See [covid-api, issue 53](https://github.com/NASA-IMPACT/covid-api/issues/53)

Two possible fixes:
1. Now that the `agriculture/` folder has been cleaned up to contain only `Cropmonitor*` files, we update the `s3_location` of the dataset's metadata to point to `agriculture` instead of `agriculture-cropmonitor`
- Requires no moving of files in S3
- Requires a re-deploy of the API 
2. Copy all files in `agriculture` to `agriculture-cropmonitor` as a temp fix
- Requires no redeploy of API 
- Requires duplicating (temporarily) files in S3

**Comment by olafveerman** [comment]
:facepalm: I missed the `-cropmonitor`. Files are moved and renamed. The agriculture layer is working again.

Thanks @leothomas
