### ISSUE TITLE
Spotlight specific layers show everywhere

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#449]
The following datasets show on every area (spotlight and global):

* agriculture Togo
* water quality Great Lakes TSM
* water quality Great Lakes Chla

**Comment by leothomas** [comment]
The API discerns between spotlight specific and global datasets by searching for the string `"{spotlightId}"` in the `tile.url` field of the dataset's metadata. Agriculture togo, water quality great lakes TSM and Chla are all spotlight specific, but do not have the string `"{spotlightId}"` in their metadata (since the entire dataset is specific to a single spotlight), so the API considers them to be global. 

As a quick fix I will update the `_get_global_datasets()` method to also ignore `togo-ag`, `wq-gl-chla` and `wq-gl-tsm`, in addition to any datasets with `"{spotlightId}"` in the `tile.url`. This will require a re-deploy of the API.

We should also, at a later date, discuss/implement a better way of discerning between global and spotlight datasets without having to hardcode the 3 datasets above
