### ISSUE TITLE
NO2 compare not requesting correct tiles

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#492]
From #490. There is an issue with the NO2 comparison:

> # NO2
> The issue is coming from the tiles under the `compare` section of the dataset. The front end end is requesting a URL with a `{date}` string in the filename, in the format `YYYYMM` (eg: `201507` in the URL you posted), whereas the comparison tiles stored under `s3://covid-eo-data/OMNO2d_HRMBaseline` just have a number `01` through `12` in their filename.
![image](https://user-images.githubusercontent.com/11858457/100789394-6382ab00-33e4-11eb-9d38-890d4cdccfea.png)
> 
> Am I correct in saying that the idea behind the "Compare" tiles is to compare a given N02 tile with the 5 year average for that month (ie: 202001 should be compared with the `average(201901, 201801, 201701, 201601, 201501)`which is stored under a single tile with just `01` in its filename?
> 
> If that's the case we need to figure out a way for the frontend to be able to request something like `07` instead of `201507` when requesting a "Compare" tile. 
> 
> Taking the url you posted, replacing `201507` with just `07` loads correctly: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/4/7/9@1x?url=s3://covid-eo-data/OMNO2d_HRMBaseline/OMI_trno2_0.10x0.10_Baseline_07_Col3_V4.nc.tif&esampling_method=bilinear&bidx=1&rescale=0%2C1.5e16&color_map=custom_no2&color_formula=gamma%20r%201.05
>

**Comment by olafveerman** [comment]
> Am I correct in saying that the idea behind the "Compare" tiles is to compare a given N02 tile with the 5 year average for that month

@leothomas Yes, that is correct. The baseline product shows the average NO2 over the last 5 years for a particular month.

@danielfdsilva Do you have a suggestion on the best way to solve this?

**Comment by danielfdsilva** [comment]
@olafveerman @leothomas From a configuration standpoint everything seems correct (sort of)

This is the current config
https://github.com/NASA-IMPACT/covid-dashboard/blob/b28694847473015b0178e499d85184bb2647aa8e/app%2Fassets%2Fscripts%2Fcomponents%2Fcommon%2Flayers%2Flayer-no2.js#L9-L21

As you can see the `{date}` on the url is being replace with `monthOnly` so that should be correct.
The compare date is subtracting 2y but since we are only taking the month into account this doesn't really matter. The label also says 2y which should be corrected.

Is there another problem that I'm not aware of?

**Comment by olafveerman** [comment]
This was fixed in the latest release of the API. The layers were loaded with `0` opacity
